version: '3.5'

services:

  simple-api:
    container_name: simple-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3001'
    networks:
      - proxynet
    environment:
      - NODE_ENV=development
 
networks:
  proxynet:
    name: custom_network
    external: true